app/urls.py
from django.urls import path
from .views import *


app_name = "ecomapp"
urlpatterns = [

    path("", HomeView.as_view(), name="home"),
    path("o-nas/", AboutView.as_view(), name="about"),
    path("kontakt/", ContactView.as_view(), name="contact"),
    path("kategorie/", AllProductsView.as_view(), name="allproducts"),
    path("produkt/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),

    path("dodaj-do-koszyka-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("moj-koszyk/", MyCartView.as_view(), name="mycart"),
    path("koszyk/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("pusty-koszyk/", EmptyCartView.as_view(), name="emptycart"),

    path("zamowienie/", CheckoutView.as_view(), name="checkout"),

    path("rejestracja/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("wyloguj/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("logowanie/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profil/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profil/zamowienie-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("szukaj/", SearchView.as_view(), name="search"),

    path("przypomnij-haslo/", PasswordForgotView.as_view(), name="passworforgot"),
    path("zresetuj-haslo/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    imię_i_nazwisko = models.CharField(max_length=200)
    adres = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.imię_i_nazwisko


class Categorie(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    category = models.ForeignKey(Categorie, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products")
    marked_price = models.PositiveIntegerField()
    selling_price = models.PositiveIntegerField(default=0)
    description = models.TextField()
    warranty = models.CharField(max_length=300)
    return_policy = models.CharField(max_length=300)
    view_count = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="products/images/")

    def __str__(self):
        return self.product.title


class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)


class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Otrzymano zamówienie", "Otrzymano zamówienie"),
    ("Przetwarzanie zamówienia", "Przetwarzanie zamówienia"),
    ("W drodze", "W drodze"),
    ("Zamówienie zrealizowane", "Zamówienie zrealizowane"),
    ("Zamówienie anulowane", "Zamówienie anulowane"),
)

METHOD = (
    ("Za pobraniem", "Za pobraniem"),
    ("PayPal", "PayPal"),
    ("Przelewy24", "Przelewy24"),
)


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    zamówiony_przez = models.CharField(max_length=200) #, default=str(Customer))
    adres_wysyłki = models.CharField(max_length=200)
    telefon = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    metoda_płatności = models.CharField(
        max_length=20, choices=METHOD, default="Za pobraniem")
    payment_completed = models.BooleanField(
        default=False, null=True, blank=True)

    def __str__(self):
        return "Order: " + str(self.id)

templates/PayPalrequest.html
<html>
<head>
    
</head>
<body>
    <h3>Kwota Twojego zamówienia to {{order.total}} zł.</h3>
    
    <button id="payment-button">Zapłać z PayPal</button>
    <a href="/">Powrór na stronę główną.</a>

    <!-- Paste this code anywhere in you body tag -->
</body>
</html>

templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Dodaj do koszyka{% endblock %}

{% block content %}
<div class="container">
    <h3>Produkt został pomyślnie dodany do koszyka.</h3>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}

{% block title %} Kategorie {% endblock %}

{% block content %}
<div class="container">
    <h3>Wszystkie kategorie</h3><hr>
    {% for cat in allcategories %}
    <h4>{{cat.title}}</h4><hr>
    <div class="row">
        {% for p in cat.product_set.all %}
        <div class="col-md-3">
            <div class="m-4"><center>
                <h4><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 2500; object-fit: cover;">
                {% if p.selling_price != p.marked_price %}
                <p class="mt-3">Cena: <s>{{p.marked_price}} zł</s> <b>{{p.selling_price}} zł</b></p>
                {% else %}
                <p class="mt-3">Cena: {{p.marked_price}} zł</p>
                {% endif %}
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Dodaj do koszyka</a>
            </center></div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    {% comment %} <nav class="navbar navbar-expand-lg navbar-dark bg-info"> {% endcomment %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    {% comment %} <nav class="navbar navbar-dark bg-dark"> {% endcomment %}
    {% comment %} <nav class="navbar navbar-expand-lg navbar-light bg-light"> {% endcomment %}
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">Sklep Django</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecomapp:home' %}">Menu główne <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Kategorie</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:mycart' %}">Koszyk {{cart.cartproduct.quantity}}</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Moje konto
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">Mój profil</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Wyloguj</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Zarejestruj się</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Zaloguj się</a>
                {% endif %}
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
            <input name="keyword" class="form-control mr-sm-2" type="search" placeholder="Wpisz szukaną frazę" aria-label="Search" required>
            <button class="btn btn-success my-2 my-sm-0" type="submit">Szukaj..</button>
            </form>
        </div>
        </nav>
    <hr>

   
    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

{% block title %}Zamówienie {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3>Przedmioty w koszyku</h3>
            <a href="{% url 'ecomapp:mycart' %}">Zaktualizuj koszyk</a>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Produkt</th>
                        <th>Ocena</th>
                        <th>Ilość</th>
                        <th>Suma</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right"> Łącznie: </th>
                        <th>{{cart.total}} zł </th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <h3>Dane do wysyłki:</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-info">Kup teraz</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/contactus.html
{% extends 'base.html' %}

{% block title %}Kontakt{% endblock %}

{% block content %}
    <h1>Skontaktuj się z nami:</h1>
    <p></p>
    <p></p>
{% endblock %}

templates/customerprofile.html
{% extends 'base.html' %}

{% block title %}Profil{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h3>Szczegółowe informacje</h3><hr>
            <p><span class="font-weight-bold">Imię i nazwisko: </span> {{customer.imię_i_nazwisko}}</p>
            <p><span class="font-weight-bold">E-mail: </span> {{customer.user.email}}</p>
            {% if customer.address %}
            <p><span class="font-weight-bold">Adres: </span> {{customer.address}}</p>
            {% endif %}
            <p><span class="font-weight-bold">Dołączył: </span> {{customer.joined_on}}</p>
        </div>
        <div class="col-md-8">
            <h3>Wcześniejsze zamówienia</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>ID zamówienia</th>
                        <th>Suma</th>
                        <th>Zamówiono dnia</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for ord in orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'ecomapp:customerorderdetail' ord.pk %}"> #_{{ord.id}}</a></td>
                        <td>{{ord.total}} zł</td>
                        <td>{{ord.created_at|timesince}} temu</td>
                        <td>{{ord.order_status}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Rejestracja klienta{% endblock %}

{% block content %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Panel rejestracyjny</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Zarejestruj się</button>
            </form>
            <p> Posiadasz już konto? <a href="{% url 'ecomapp:customerlogin' %}">Zaloguj się.</a></p>
        </div>
    </div>
</div>
{% endblock %}

templates/esewarequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        #myform{
            display: none;
        }
    </style>
</head>
<body>
    <h3 style="text-align: center;">Zostaniesz przekierowany na stronę esewa..</h3>
    <form action="https://uat.esewa.com.np/epay/main" method="POST" id="myform">
        <input value="{{order.total}}" name="tAmt" type="hidden">
        <input value="{{order.total}}" name="amt" type="hidden">
        <input value="0" name="txAmt" type="hidden">
        <input value="0" name="psc" type="hidden">
        <input value="0" name="pdc" type="hidden">
        <input value="epay_payment" name="scd" type="hidden">
        <input value="order_{{order.id}}" name="pid" type="hidden">
        <input value="http://127.0.0.1:8000/esewa-verify/" type="hidden" name="su">
        <input value="{{request.build_absolute_uri}}" type="hidden" name="fu">
        <input value="Submit" type="submit">
    </form>

    <script>
        setTimeout(function(){
            document.getElementById("myform").submit()
        }, 500)
        
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Menu główne{% endblock %}

{% block content %}
<div class="container">

    <h1 class="text-center">Witaj w naszym sklepie. </h1>
    <hr>
    <div class="row mt-3">
        {% for p in product_list %}
        <div class="col-md-3 card">
            <div class="m-4">
                <h4><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
                <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                {% if p.selling_price != p.marked_price %}
                <p class="mt-3">Cena: <s>{{p.marked_price}} zł</s> <b>{{p.selling_price}} zł</b></p>
                {% else %}
                <p class="mt-3">Cena: {{p.marked_price}} zł</p>
                {% endif %}
                <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Dodaj do koszyka</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <nav aria-label="...">
        <ul class="pagination">
            {% if product_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.previous_page_number }}">Poprzedni1</a>
              </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Poprzedni</a>
            </li>
            {% endif %}

            {% for i in product_list.paginator.page_range %}
            {% if i == product_list.number %}
            <li class="page-item active"><a class="page-link">{{i}}</a></li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
            {% endfor %}

            {% if product_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ product_list.next_page_number }}">Next1</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Następny</a>
            </li>
            {% endif %}
        </ul>
      </nav>

</div>
{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %} My cart{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Produkty w koszyku</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th></th>
                        <th>Produkt</th>
                        <th>Cena</th>
                        <th>Ilość</th>
                        <th>Suma</th>
                        <th>Akcja</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}} zł</td>
                        <td>{{cp.quantity}} szt.</td>
                        <td>{{cp.subtotal}} zł</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-warning"> - </a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-danger"> x </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Razem</th>
                        <th>{{cart.total}} zł</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'ecomapp:emptycart' %}">Pusty koszyk</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'ecomapp:checkout' %}"> Kup teraz </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

templates/passwordreset.html
{% extends 'base.html' %}

{% block title %}Zresetuj hasło{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Zresetuj hasło</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/productdetail.html
{% extends 'base.html' %}

{% block title %}{{product.title}}{% endblock %}

{% block content %}
<div class="container">
    <h3>Produkt: {{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-4">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
            <div class="row">
                {% for pi in product.productimage_set.all %}
                <div class="col-md-4 p-3">
                    <a href="{{pi.image.url}}" target="_blank">
                        <img src="{{pi.image.url}}" class="img-fluid" style="height: 100px; object-fit: contain;" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8">
            <h4>{{product.title}} (Wyświetlono {{product.view_count}} razy)</h4>
            <h5>Kategoria: {{product.category}}</h5>
            {% if p.selling_price != p.marked_price %}
            <h5>Cena: <s>{{product.marked_price}} zł</s> <b>{{product.selling_price}} zł </b></h5>
            {% else %}
            <h5 class="mt-3">Cena: {{product.marked_price}} zł</h5>
            {% endif %}
            <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-info">Dodaj do koszyka</a>
            <hr>
            {% if product.warranty %}
                <p class="text-info">Gwarancja: {{product.warranty}}</p>
            {% endif %}
            {% if product.return_policy %}
                <p class="text-info">Czas na zwrot: {{product.return_policy}}</p>
            {% endif %}
            {% if product.warranty and result.return_policy%}
            <hr>
            {% endif %}
            <p>{{product.description}}</p>
        </div>
    </div>

</div>
{% endblock %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Wyszukiwanie {% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Wyniki wyszukiwania dla: <span class="text-info">"{{request.GET.keyword}}"</span></h3>
            <hr>
            {% for result in results %}
            <div class="row">
                <div class="col-md-3">
                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                </div>
                <div class="col-md-9">
                    <h4><a href="{% url 'ecomapp:productdetail' result.slug %}">{{result.title}}</a></h4>
                    <p>{{result.description|truncatewords:50}}</p>
                    {% if result.return_policy %}
                        <p>Czas na zwrot: {{result.return_policy}}</p>
                    {% endif %}
                    <a href="{% url 'ecomapp:addtocart' result.id %}" class="btn btn-primary">Dodaj do koszyka</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}